# File: deploy/compose/docker-compose.micro.yaml
# version: "3.9"
services:
  api-gateway:
    build:
      context: ../..
      dockerfile: deploy/docker/microservices/Dockerfile.gateway
    ports:
      - "8080:8080"
    environment:
      REDIRECT_URL: "http://redirect:8001"
      ANALYTICS_URL: "http://analytics:8002"
      RATELIMIT_URL: "http://ratelimit:8003"
    depends_on: [redirect, analytics, ratelimit, redis]
  redirect:
    build:
      context: ../..
      dockerfile: deploy/docker/microservices/Dockerfile.redirect
    environment:
      REDIS_URL: "redis://redis:6379/0"
      GATEWAY_BASE_URL: "http://localhost:8080"
    depends_on: [redis]
  analytics:
    build:
      context: ../..
      dockerfile: deploy/docker/microservices/Dockerfile.analytics
    environment:
      REDIS_URL: "redis://redis:6379/0"
    depends_on: [redis]
  ratelimit:
    build:
      context: ../..
      dockerfile: deploy/docker/microservices/Dockerfile.ratelimit
    environment:
      REDIS_URL: "redis://redis:6379/0"
      RL_LIMIT_PER_MIN: 120
      RL_WINDOW_SEC: 60
    depends_on: [redis]
  redis:
    build:
      context: ../..
      dockerfile: deploy/docker/microservices/Dockerfile.redis
    ports: ["6379:6379"]
networks:
  default:
    name: urlshortener-net
