services:
  layered-app:
    image: abchalla/urlshort-layered-app:day1-v2
    environment:
      REDIS_URL: "redis://redis-master:6379/0"
      GATEWAY_BASE_URL: "http://localhost:8081"
      GRPC_PORT: 50051
      RL_LIMIT_PER_MIN: 120
      RL_WINDOW_SEC: 60
    depends_on: [redis-master]

  nginx:
    image: abchalla/urlshort-layered-nginx:day1-v2
    ports:
      - "8088:8081"
    depends_on: [layered-app]

  redis-master:
    image: abchalla/urlshort-layered-redis-master:day1-v1
    volumes: [ "redis-master-data:/data" ]

  redis-replica:
    image: abchalla/urlshort-layered-redis-replica:day1-v1
    environment:
      REDIS_MASTER_HOST: "redis-master"
    depends_on: [redis-master]
    volumes: [ "redis-replica-data:/data" ]

  analytics-worker:
    image: abchalla/urlshort-layered-worker:day1-v2
    environment:
      REDIS_URL: "redis://redis-master:6379/0"
      WORKER_INTERVAL: 10
    depends_on: [redis-master]

volumes:
  redis-master-data:
  redis-replica-data:

networks:
  default:
    name: urlshortener-layered-simple