services:
  api-gateway:
    image: abchalla/urlshort-gateway:day1-v2
    environment:
      REDIRECT_URL:  "http://redirect:8001"
      ANALYTICS_URL: "http://analytics:8002"
      RATELIMIT_URL: "http://ratelimit:8003"
    ports:
      - "8080:8080"
    restart: unless-stopped

  redirect:
    image: abchalla/urlshort-redirect:day1-v2
    environment:
      REDIS_URL: "redis://redis:6379/0"
      # This is what the short_url uses:
      GATEWAY_BASE_URL: "${GATEWAY_BASE_URL:-http://localhost:8080}"
    restart: unless-stopped

  analytics:
    image: abchalla/urlshort-analytics:day1-v2
    environment:
      REDIS_URL: "redis://redis:6379/0"
    restart: unless-stopped

  ratelimit:
    image: abchalla/urlshort-ratelimit:day1-v2
    environment:
      REDIS_URL: "redis://redis:6379/0"
      RL_LIMIT_PER_MIN: "${RL_LIMIT_PER_MIN:-120}"
      RL_WINDOW_SEC: "${RL_WINDOW_SEC:-60}"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

networks:
  default:
    name: urlshortener-net
